//===========================================================================
//  APPLICATION SETTINGS
//===========================================================================

//===========================================================================
//  ONLY CHANGE THE FOLLOWING IF YOU KNOW WHAT YOU ARE DOING
//===========================================================================
def dnsRecord
def dnsDomain
def dnsResourceGroup

def labelFile = "./dist/assets/labels.txt"
def sonarFile = "./config/sonar-project.properties"

def dockerNetwork = "easyware"

def traefikResolver = "easywareresolver"

def dnsCNAMEvalue = "obelix.easyware.io"

def myNexusHostname = "nexus.easyware.io"
def myNexusHostedRepoPort = "8083"
def myNexusGroupRepoPort = "8082"
def dockerImageGroup = "easyware"
def applicationName
def applicationVersion

pipeline {
	agent {
        docker {
            image 'dkorber/java-node:latest' 
            args '-p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock --name jenkins-temp' 
        }
    }
	environment {
        CRED_NEXUS = credentials('easywareNexusAdmin')
		CRED_SONAR = credentials('easywareSonarJenkins')
    }

	stages {

		stage("Prepare environment") {
			steps{
				script {
					// Read application name and version from package.json file
					def props = readJSON file: './package.json'					
					applicationName = props.name
					applicationVersion = props.version
					dnsRecord = props.jenkins.dnsRecord
					dnsDomain = props.jenkins.dnsDomain
					dnsResourceGroup = props.jenkins.dnsResourceGroup

					echo "applicationName: ${applicationName}"
					echo "applicationVersion: ${applicationVersion}"
					sh "npm config set registry https://${myNexusHostname}/repository/easyware-npm-group"
					sh "docker login -u ${CRED_NEXUS_USR} -p ${CRED_NEXUS_PSW} ${myNexusHostname}:${myNexusHostedRepoPort}"

				}
			}
		}		

		stage("Install packages") {
			steps{
				script {
					echo "Installing packages for ${applicationName}"	
					sh "npm install"
				}
			}
		}

		stage("Set sonar settings") {
			steps{
				script{
					sh "echo 'sonar.login=${CRED_SONAR_USR}' >> ${sonarFile}"
					sh "echo 'sonar.password=${CRED_SONAR_PSW}' >> ${sonarFile}"
					sh "echo 'sonar.projectKey=${applicationName}' >> ${sonarFile}"
					sh "echo 'sonar.projectName=${applicationName}' >> ${sonarFile}"
				}
			}
		}

		stage("Lint") {
			steps{
				script {
					echo "Linting ${applicationName}"
					sh "npm run sonar"
				}
			}
		}

		stage("Build app") {
			steps{
				script {
					echo "Building ${applicationName} app"
					sh "npm run build:prod"
				}
			}
		}

		stage("Build docker") {
			steps{
				script {
					echo "Building docker image for ${applicationName}."
					sh "docker build -t ${dockerImageGroup}/${applicationName} ."
					sh "docker tag ${dockerImageGroup}/${applicationName} ${myNexusHostname}:${myNexusHostedRepoPort}/${dockerImageGroup}/${applicationName}:${applicationVersion}"
					sh "docker tag ${dockerImageGroup}/${applicationName} ${myNexusHostname}:${myNexusHostedRepoPort}/${dockerImageGroup}/${applicationName}:latest"
					sh "docker push ${myNexusHostname}:${myNexusHostedRepoPort}/${dockerImageGroup}/${applicationName}:${applicationVersion}"
					sh "docker push ${myNexusHostname}:${myNexusHostedRepoPort}/${dockerImageGroup}/${applicationName}:latest"
				}
			}
		}

		stage("Create DNS record") {
			steps{
				script{
					echo "Creating DNS record ${dnsRecord}.${dnsDomain}"
					def azureCmd = "az network dns record-set cname set-record -g ${dnsResourceGroup} -z ${dnsDomain} -n ${dnsRecord} -c ${dnsCNAMEvalue}"
					sh "docker run dkorber/azure ${azureCmd}"
				}
			}
		}

		stage("Prepare docker deployment") {
			steps{
				script{
					sh "touch ${labelFile}"
					sh "echo 'traefik.enable=true' >> ${labelFile}"
					sh "echo 'traefik.http.routers.template.entrypoints=websecure' >> ${labelFile}"
					sh "echo 'traefik.http.routers.template.rule=Host(`${dnsRecord}.${dnsDomain}`)' >> ${labelFile}"
					sh "echo 'traefik.http.routers.template.tls.certresolver=${traefikResolver}' >> ${labelFile}"
				}
			}
		}

		stage("Start docker") {
			steps{
				script {
					echo "Deploying ${applicationName}"
					sh "docker stop ${applicationName} || true && docker rm ${applicationName} || true"	
					sh """docker run -d \
					                 --network ${dockerNetwork} \
					                 --name ${applicationName} \
									 --label-file ${labelFile} \
									 ${dockerImageGroup}/${applicationName}"""
					sh "rm ${labelFile}"					
				}
			}
		}

		stage("Prune docker") {
			steps{
				script {
					echo "Pruning ${applicationName}"
					sh "docker system prune"		
				}
			}
		}

	}
}